//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messaging
{
    using Models;
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveableFee
    {
        public int ID { get; set; }
        public int AdmissionID { get; set; }
        public System.DateTime ForMonth { get; set; }
        public System.DateTime DueDate { get; set; }
        public double TuitionFe { get; set; }
        public double Misc { get; set; }
        public double TransportFee { get; set; }
        public double Arrears { get; set; }
        public double Fine { get; set; }
        public double LateFee { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public int UserID { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<int> LastEditBy { get; set; }
        public Nullable<double> AdmissionFee { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> LastFineDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> ComCharges { get; set; }
        public Nullable<bool> ApplyLateFee { get; set; }
    
        public virtual Admission Admission { get; set; }
    }
}
