//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore;
    using smsCore.Data.Tenant;
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    public partial class SchoolEntities : IdentityDbContext<ApplicationUser>
    {
        //public SchoolEntities(DbContextOptions<SchoolEntities> option):base(option) 
        //{
        //}
        //protected override void OnConfiguring(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder optionsBuilder)
        //{

        //    base.OnConfiguring(optionsBuilder);
        //}

        private readonly ITenantProvider _tenantProvider;

        public SchoolEntities(ITenantProvider tenantProvider)
        {
            _tenantProvider = tenantProvider;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var tenantName = _tenantProvider.GetTenantName();
            var tenant = _tenantProvider.GetTenant(tenantName);
            optionsBuilder.UseSqlServer(tenant.ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }

        public object ExecuteSP(string v, List<SqlParameter> collection2)
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<AddmissionWaitingList> AddmissionWaitingLists { get; set; }
        public virtual DbSet<Admission> Admissions { get; set; }
        public virtual DbSet<ApplicationLeave> ApplicationLeaves { get; set; }
        public virtual DbSet<AssetStock> AssetStocks { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<CallRecord> CallRecords { get; set; }
        public virtual DbSet<Campus> Campuses { get; set; }
        public virtual DbSet<CampusUser> CampusUsers { get; set; }
        public virtual DbSet<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassFeeGroup> ClassFeeGroups { get; set; }
        public virtual DbSet<ClassSection> ClassSections { get; set; }
        public virtual DbSet<ClassSubject> ClassSubjects { get; set; }
        public virtual DbSet<ComSub> ComSubs { get; set; }
        public virtual DbSet<DailyCash> DailyCashes { get; set; }
        public virtual DbSet<DOBChanx> DOBChanges { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<EmployeeAttendanceType> EmployeeAttendanceTypes { get; set; }
        public virtual DbSet<EmployeeAward> EmployeeAwards { get; set; }
        public virtual DbSet<EmployeeExperinceSubject> EmployeeExperinceSubjects { get; set; }
        public virtual DbSet<EmployeeExprience> EmployeeExpriences { get; set; }
        public virtual DbSet<EmployeeMobile> EmployeeMobiles { get; set; }
        public virtual DbSet<EmployeeShortLeave> EmployeeShortLeaves { get; set; }
        public virtual DbSet<EmployeeThumbImpression> EmployeeThumbImpressions { get; set; }
        public virtual DbSet<EmployeeWaitingList> EmployeeWaitingLists { get; set; }
        public virtual DbSet<ExamDate> ExamDates { get; set; }
        public virtual DbSet<ExamHeld> ExamHelds { get; set; }
        public virtual DbSet<ExamRemark> ExamRemarks { get; set; }
        public virtual DbSet<ExamRemarksDetail> ExamRemarksDetails { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<ExamsRule> ExamsRules { get; set; }
        public virtual DbSet<ExpellDetail> ExpellDetails { get; set; }
        public virtual DbSet<FeeDiscount> FeeDiscounts { get; set; }
        public virtual DbSet<FeeGroup> FeeGroups { get; set; }
        public virtual DbSet<FeeSlipDetail> FeeSlipDetails { get; set; }
        public virtual DbSet<FeeSlipPaymentMethod> FeeSlipPaymentMethods { get; set; }
        public virtual DbSet<FeeSlipReceipt> FeeSlipReceipts { get; set; }
        public virtual DbSet<FeeSlip> FeeSlips { get; set; }
        public virtual DbSet<FeeStructure> FeeStructures { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<FineDeduction> FineDeductions { get; set; }
        public virtual DbSet<FreeAdmission> FreeAdmissions { get; set; }
        public virtual DbSet<Homework> Homework { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<HostelAdmission> HostelAdmissions { get; set; }
        public virtual DbSet<HostelAttendance> HostelAttendances { get; set; }
        public virtual DbSet<IssuedBoardCertificate> IssuedBoardCertificates { get; set; }
        public virtual DbSet<IssuedBook> IssuedBooks { get; set; }
        public virtual DbSet<IssuedBooksToStaff> IssuedBooksToStaffs { get; set; }
        public virtual DbSet<IssuedCertificate> IssuedCertificates { get; set; }
        public virtual DbSet<LeavedStaff> LeavedStaffs { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<LibraryBookList> LibraryBookLists { get; set; }
        public virtual DbSet<LibraryBookRecord> LibraryBookRecords { get; set; }
        public virtual DbSet<LibraryIssuedBook> LibraryIssuedBooks { get; set; }
        public virtual DbSet<LibraryIssuedBooksToStaff> LibraryIssuedBooksToStaffs { get; set; }
        public virtual DbSet<LibraryListOfBook> LibraryListOfBooks { get; set; }
        public virtual DbSet<ListOfBook> ListOfBooks { get; set; }
        public virtual DbSet<MenuAction> MenuActions { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Privlidge> Privlidges { get; set; }
        public virtual DbSet<MessageRecord> MessageRecords { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<MobileDevice> MobileDevices { get; set; }
        public virtual DbSet<MobileMessage> MobileMessages { get; set; }
        public virtual DbSet<OldJinnahian> OldJinnahians { get; set; }
        public virtual DbSet<ParentsVisit> ParentsVisits { get; set; }
        public virtual DbSet<PeriodMaster> PeriodMasters { get; set; }
        public virtual DbSet<ProfessionalTraining> ProfessionalTrainings { get; set; }
        public virtual DbSet<ProhibitedMaterial> ProhibitedMaterials { get; set; }
        public virtual DbSet<PublicMobile> PublicMobiles { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<RatingMaster> RatingMasters { get; set; }
        public virtual DbSet<RatingParticipant> RatingParticipants { get; set; }
        public virtual DbSet<ReAdmission> ReAdmissions { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<ResultSummary> ResultSummaries { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<SchoolLeaveSchedule> SchoolLeaveSchedules { get; set; }
        public virtual DbSet<SchoolLogo> SchoolLogoes { get; set; }
        public virtual DbSet<ScienceLabItem> ScienceLabItems { get; set; }
        public virtual DbSet<ScienceLabItemsStock> ScienceLabItemsStocks { get; set; }
        public virtual DbSet<ScienceLabMissingItem> ScienceLabMissingItems { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SelectedForCadetCollege> SelectedForCadetColleges { get; set; }
        public virtual DbSet<SignatureSpeciman> SignatureSpecimen { get; set; }
        public virtual DbSet<SLC> SLCs { get; set; }
        public virtual DbSet<SMSApplicationProperty> SMSApplicationProperties { get; set; }
        public virtual DbSet<StudentAlumni> StudentAlumnis { get; set; }
        public virtual DbSet<StudentAttendanceType> StudentAttendanceTypes { get; set; }
        public virtual DbSet<StudentAttendence> StudentAttendences { get; set; }
        public virtual DbSet<StudentComplaign> StudentComplaigns { get; set; }
        public virtual DbSet<StudentMobile> StudentMobiles { get; set; }
        public virtual DbSet<StudentPhoto> StudentPhotos { get; set; }
        public virtual DbSet<StudentPreviousEducation> StudentPreviousEducations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsTransport> StudentsTransports { get; set; }
        public virtual DbSet<StudentsWarning> StudentsWarnings { get; set; }
        public virtual DbSet<StudentThumbImpression> StudentThumbImpressions { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TaskDairy> TaskDairies { get; set; }
        public virtual DbSet<tbl_Designation> tbl_Designation { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<TeachingClass> TeachingClasses { get; set; }
        public virtual DbSet<TeachingSubject> TeachingSubjects { get; set; }
        public virtual DbSet<TimeConsumptionForResultEntry> TimeConsumptionForResultEntries { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<UnwantedClient> UnwantedClients { get; set; }
        public virtual DbSet<UserDefinition> UserDefinitions { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<VoteByStudent> VoteByStudents { get; set; }
        public virtual DbSet<WebSite> WebSites { get; set; }
        public virtual DbSet<ActiveRating> ActiveRatings { get; set; }
        public virtual DbSet<SchoolInfo> SchoolInfoes { get; set; }

        public virtual DbSet<tbl_FinancialYear> FinancialYears { get; set; }
        public virtual DbSet<tbl_Company> Company { get; set; }
        public virtual DbSet<tbl_AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<tbl_AccountLedger> AccountLedgers { get; set; }
        public virtual DbSet<tbl_VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<tbl_LedgerPosting> LedgerPostings { get; set; }
        public virtual DbSet<tbl_SalaryPackage> SalaryPackages { get; set; }
        public virtual DbSet<tbl_SalaryPackageDetails> SalaryPackageDetails { get; set; }
        public virtual DbSet<tbl_PayHead> PayHeads { get; set; }
        public virtual DbSet<tbl_MonthlySalary> MonthlySalaries { get; set; }
        public virtual DbSet<tbl_MonthlySalaryDetails> MonthlySalaryDetails { get; set; }
        public virtual DbSet<tbl_SalaryPayment> SalaryPayments { get; set; }

        public virtual DbSet<tbl_PaymentMaster> PaymentMasters { get; set; }
        public virtual DbSet<tbl_PaymentDetails> PaymentDetails { get; set; }

        public virtual DbSet<tbl_ReceiptMaster> ReceiptMasters { get; set; }
        public virtual DbSet<tbl_ReceiptDetails> ReceiptDetails { get; set; }

        public virtual DbSet<tbl_JournalMaster> JournalMasters { get; set; }
        public virtual DbSet<tbl_JournalDetails> JournalDetails { get; set; }

        public virtual DbSet<tbl_ExpenseMaster> ExpenseMasters { get; set; }
        public virtual DbSet<tbl_ExpenseDetails> ExpenseDetails { get; set; }

        public virtual DbSet<tbl_BudgetMaster> BudgetMasters { get; set; }
        public virtual DbSet<tbl_BudgetDetails> BudgetDetails { get; set; }

        public virtual DbSet<PublicMenu> PublicMenus { get; set; }
        public virtual DbSet<PublicPostCategory> PublicPostCategories { get; set; }
        public virtual DbSet<PublicContentPost> PublicPosts { get; set; }
        public virtual DbSet<PublicPage> PublicPages { get; set; }
        public virtual DbSet<PublicSlider> PublicSliders { get; set; }
    }
}
