//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AddmissionWaitingList
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string Address { get; set; }
        public int ClassID { get; set; }
        public string Phone { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Class Class { get; set; }
    }
}
