//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Admission
    {
        public Admission()
        {
            this.CallRecords = new HashSet<CallRecord>();
            this.ExamRemarks = new HashSet<ExamRemark>();
            this.FeeSlips = new HashSet<FeeSlip>();
            this.RatingParticipants = new HashSet<RatingParticipant>();
            this.ReAdmissions = new HashSet<ReAdmission>();
            this.Results = new HashSet<Result>();
            this.StudentAttendences = new HashSet<StudentAttendence>();
            this.StudentPreviousEducations = new HashSet<StudentPreviousEducation>();
        }
    
        public bool IsExpell { get; set; }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int ClassSectionID { get; set; }
        public int StudentID { get; set; }
        public int Session { get; set; }
        public int CampuseID { get; set; }
    
        [ForeignKey("CampuseID")]
        public virtual Campus Campus { get; set; }
        public virtual Student Student { get; set; }

        public virtual ClassSection ClassSection { get; set; }
        
        public virtual ICollection<CallRecord> CallRecords { get; set; }
        
        public virtual ICollection<ExamRemark> ExamRemarks { get; set; }
        
        public virtual ICollection<FeeSlip> FeeSlips { get; set; }
        
        public virtual ICollection<RatingParticipant> RatingParticipants { get; set; }
        
        public virtual ICollection<ReAdmission> ReAdmissions { get; set; }
        
        public virtual ICollection<Result> Results { get; set; }
        
        public virtual ICollection<StudentAttendence> StudentAttendences { get; set; }
        
        public virtual ICollection<StudentPreviousEducation> StudentPreviousEducations { get; set; }
    }
}
