//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.IssuedBooks = new HashSet<IssuedBook>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int AccessionNo { get; set; }
        public string ClassficationNo { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Edition { get; set; }
        public string Subject { get; set; }
        public string YearOfPublishing { get; set; }
        public string VolumeNo { get; set; }
        public string Language { get; set; }
        public string Pages { get; set; }
        public string Price { get; set; }
        public string Source { get; set; }
        public string ShelfNo { get; set; }
        public string PresentPosition { get; set; }
        public bool IsIssuable { get; set; }
        public string Remarks { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Translator { get; set; }
        public string Cornor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuedBook> IssuedBooks { get; set; }
    }
}
