//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Campuses")] 
    public partial class Campus
    {
        public Campus()
        {
            this.AddmissionWaitingLists = new HashSet<AddmissionWaitingList>();
            this.Admissions = new HashSet<Admission>();
            this.ClassFeeGroups = new HashSet<ClassFeeGroup>();
            this.ClassSections = new HashSet<ClassSection>();
            this.ClassSubjects = new HashSet<ClassSubject>();
            this.Drivers = new HashSet<Driver>();
            this.ExamDates = new HashSet<ExamDate>();
            this.ExamHelds = new HashSet<ExamHeld>();
            this.FeeSlipPaymentMethods = new HashSet<FeeSlipPaymentMethod>();
            this.FeeStructures = new HashSet<FeeStructure>();
            this.Hostels = new HashSet<Hostel>();
            this.Libraries = new HashSet<Library>();
            this.RatingMasters = new HashSet<RatingMaster>();
            this.SchoolLeaveSchedules = new HashSet<SchoolLeaveSchedule>();
            this.ScienceLabItemsStocks = new HashSet<ScienceLabItemsStock>();
            this.ScienceLabMissingItems = new HashSet<ScienceLabMissingItem>();
            this.SMSApplicationProperties = new HashSet<SMSApplicationProperty>();
            this.tbl_Employee = new HashSet<tbl_Employee>();
            this.TeachingSubjects = new HashSet<TeachingSubject>();
            this.CampusUsers = new HashSet<CampusUser>();
        }
    
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string CampusName { get; set; }
        public string mailingName { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string emailId { get; set; }
        public string web { get; set; }
    
        public virtual ICollection<AddmissionWaitingList> AddmissionWaitingLists { get; set; }
        public virtual ICollection<Admission> Admissions { get; set; }
        public virtual ICollection<ClassFeeGroup> ClassFeeGroups { get; set; }
        public virtual ICollection<CampusUser> CampusUsers { get; set; }

        public virtual ICollection<ClassSection> ClassSections { get; set; }
        
        public virtual ICollection<ClassSubject> ClassSubjects { get; set; }
        
        public virtual ICollection<Driver> Drivers { get; set; }
        
        public virtual ICollection<ExamDate> ExamDates { get; set; }
        
        public virtual ICollection<ExamHeld> ExamHelds { get; set; }
        
        public virtual ICollection<FeeSlipPaymentMethod> FeeSlipPaymentMethods { get; set; }
        
        public virtual ICollection<FeeStructure> FeeStructures { get; set; }
        
        public virtual ICollection<Hostel> Hostels { get; set; }
        
        public virtual ICollection<Library> Libraries { get; set; }
        
        public virtual ICollection<RatingMaster> RatingMasters { get; set; }
        
        public virtual ICollection<SchoolLeaveSchedule> SchoolLeaveSchedules { get; set; }
        
        public virtual ICollection<ScienceLabItemsStock> ScienceLabItemsStocks { get; set; }
        
        public virtual ICollection<ScienceLabMissingItem> ScienceLabMissingItems { get; set; }
        
        public virtual ICollection<SMSApplicationProperty> SMSApplicationProperties { get; set; }
        
        public virtual ICollection<tbl_Employee> tbl_Employee { get; set; }
        
        public virtual ICollection<TeachingSubject> TeachingSubjects { get; set; }
    }
}
