//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ClassSection
    {
        public ClassSection()
        {
            this.Admissions = new HashSet<Admission>();
            this.ExamDates = new HashSet<ExamDate>();
            this.Homework = new HashSet<Homework>();
            this.TeachingSubjects = new HashSet<TeachingSubject>();
        }
    
        [Key]
        public int ID { get; set; }
        public int SectionID { get; set; }
        public int ClassID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CampusID { get; set; }
    
        
        public virtual ICollection<Admission> Admissions { get; set; }

        
        public virtual Campus Campus { get; set; }
        public virtual Class Class { get; set; }
        
        public virtual ICollection<ExamDate> ExamDates { get; set; }
        public virtual Section Section { get; set; }
        
        public virtual ICollection<Homework> Homework { get; set; }
        
        public virtual ICollection<TeachingSubject> TeachingSubjects { get; set; }
    }
}
