//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClassSubject
    {
        public ClassSubject()
        {
            this.Results = new HashSet<Result>();
        }
    
        [Key]
        public int ID { get; set; }
        public int SubjectID { get; set; }
        public int ClassID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Class Class { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
