//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Class
    {
        public Class()
        {
            this.AddmissionWaitingLists = new HashSet<AddmissionWaitingList>();
            this.ClassSections = new HashSet<ClassSection>();
            this.ClassFeeGroups = new HashSet<ClassFeeGroup>();
            this.ClassSubjects = new HashSet<ClassSubject>();
            this.ListOfBooks = new HashSet<ListOfBook>();
            this.LibraryListOfBooks = new HashSet<LibraryListOfBook>();
        }

        [Key]
        public int ID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> MaxStrenth { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ShortCode { get; set; }
    
        public virtual ICollection<AddmissionWaitingList> AddmissionWaitingLists { get; set; }
        
        public virtual ICollection<ClassSection> ClassSections { get; set; }
        
        public virtual ICollection<ClassFeeGroup> ClassFeeGroups { get; set; }
        
        public virtual ICollection<ClassSubject> ClassSubjects { get; set; }
        
        public virtual ICollection<ListOfBook> ListOfBooks { get; set; }
        
        public virtual ICollection<LibraryListOfBook> LibraryListOfBooks { get; set; }
    }
}
