//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DailyCash
    {

        [Key]
        public int ID { get; set; }
        public double Amount { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Particular { get; set; }
        public string UserID { get; set; }
    }
}
