//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DOBChanx
    {
        [Key]
        public int ID { get; set; }
        public System.DateTime OldDOB { get; set; }
        public System.DateTime NewDOB { get; set; }
        public string UserID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime EditDate { get; set; }
        public string ReferenceNo { get; set; }
    
        public virtual Student Student { get; set; }
        [ForeignKey("UserID")]
        public virtual  ApplicationUser AspNetUser { get; set; }
    }
}
