//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Driver
    {
        public Driver()
        {
            this.StudentsTransports = new HashSet<StudentsTransport>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string DriverName { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }

        public virtual ICollection<StudentsTransport> StudentsTransports { get; set; }
    }
}
