//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("EmployeeExprience")]
    public partial class EmployeeExprience
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int StfID { get; set; }
        public string Institution { get; set; }
        public string Desgnition { get; set; }
        public string From { get; set; }
        public string To { get; set; }

        [ForeignKey("StfID")]
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
