//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ExamsRule
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public double APlus { get; set; }
        public double B { get; set; }
        public double C { get; set; }
        public double D { get; set; }
        public double E { get; set; }
        public int CoreFail { get; set; }
        public int NoneCoreFail { get; set; }
        public int CoreWithNoneCoreFail { get; set; }
        public double AtLeastPercentage { get; set; }
        public double A { get; set; }
        public double BPlus { get; set; }
        public int ExamHeldID { get; set; }
    
        public virtual ExamHeld ExamHeld { get; set; }
    }
}
