//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ExamHeld
    {
        public ExamHeld()
        {
            this.ExamDates = new HashSet<ExamDate>();
            this.ExamRemarks = new HashSet<ExamRemark>();
            this.ExamsRules = new HashSet<ExamsRule>();
            this.Results = new HashSet<Result>();
            this.ResultSummaries = new HashSet<ResultSummary>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int ExamID { get; set; }
        public bool VeiwAble { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual ICollection<ExamDate> ExamDates { get; set; }
        public virtual ICollection<ExamRemark> ExamRemarks { get; set; }
        public virtual ICollection<ExamsRule> ExamsRules { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<ResultSummary> ResultSummaries { get; set; }
    }
}
