//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ExamRemark
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int AdmissionID { get; set; }
        public int ExamHeldID { get; set; }
        public string SocBeh { get; set; }
        public string Discpline { get; set; }
        public string Manners { get; set; }
        public string OralExp { get; set; }
        public string CoTeamWork { get; set; }
        public string Confid { get; set; }
        public string Punctuality { get; set; }
        public string PhyFit { get; set; }
        public string Neatness { get; set; }
        public string Attendance { get; set; }
        public string Remarks { get; set; }
        public string UserID { get; set; }
    
        public virtual Admission Admission { get; set; }
        public virtual ExamHeld ExamHeld { get; set; }
        [ForeignKey("UserID")]
        public virtual  ApplicationUser AspNetUser { get; set; }
    }
}
