//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ExamDate
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Column("ExamDate")]
        public System.DateTime ExamDate1 { get; set; }
        public int ExamHeldID { get; set; }
        public string TimeFrom { get; set; }
        public string ToTime { get; set; }
        public double TotalMarks { get; set; }
        public int ClassSectionID { get; set; }
        public int CampusID { get; set; }
        public int SubjectID { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual ClassSection ClassSection { get; set; }
        public virtual ExamHeld ExamHeld { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
