//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ExpellDetail
    {
         public ExpellDetail()
        {
            this.SLCs = new HashSet<SLC>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Particular { get; set; }
        public int StudentID { get; set; }
        public string UserID { get; set; }
        public string LastClass { get; set; }
        public string SLCNo { get; set; }
        public string Conduct { get; set; }
        public string ExpellType { get; set; }
        public string Reason { get; set; }
        public string Dues { get; set; }
        public string LastCampus { get; set; }
        public string LastSection { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<SLC> SLCs { get; set; }
        [ForeignKey("UserID")]
        public virtual  ApplicationUser AspNetUser { get; set; }
    }
}
