//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class FeeGroup
    {
        public FeeGroup()
        {
            this.ClassFeeGroups = new HashSet<ClassFeeGroup>();
            this.FeeStructures = new HashSet<FeeStructure>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string FeeGroupName { get; set; }
    
        public virtual ICollection<ClassFeeGroup> ClassFeeGroups { get; set; }
        public virtual ICollection<FeeStructure> FeeStructures { get; set; }
    }
}
