//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FeeStructure
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int FeeTypeId { get; set; }
        public int FeeGroupId { get; set; }
        public decimal Amount { get; set; }
        public bool Revised { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string UserId { get; set; }
        public string LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public bool Deduction { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual FeeGroup FeeGroup { get; set; }
        public virtual FeeType FeeType { get; set; }
    }
}
