//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FeeSlip
    {
        public FeeSlip()
        {
            this.FeeSlipDetails = new HashSet<FeeSlipDetail>();
            this.FeeSlipReceipts = new HashSet<FeeSlipReceipt>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int AdmissionId { get; set; }
        public System.DateTime ForMonth { get; set; }
        public string UserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EditBy { get; set; }
        public Nullable<System.DateTime> EditeOn { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime LastFineDate { get; set; }
    
        public virtual Admission Admission { get; set; }
        public virtual ICollection<FeeSlipDetail> FeeSlipDetails { get; set; }
        public virtual ICollection<FeeSlipReceipt> FeeSlipReceipts { get; set; }
    }
}
