//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class FeeSlipDetail
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int FeeSlipId { get; set; }
        public int FeeTypeId { get; set; }
        public decimal Amount { get; set; }
        public decimal Discount { get; set; }
        public bool DiscountInAmount { get; set; }
    
        public virtual FeeSlip FeeSlip { get; set; }
        public virtual FeeType FeeType { get; set; }
    }
}
