//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FeeSlipReceipt
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int FeeSlipId { get; set; }
        public decimal Amount { get; set; }
        public int PaymentMethodId { get; set; }
        public string UserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EditBy { get; set; }
        public Nullable<System.DateTime> EditeOn { get; set; }
        public bool MessageSent { get; set; }
    
        [ForeignKey("PaymentMethodId")]
        public virtual FeeSlipPaymentMethod FeeSlipPaymentMethod { get; set; }
        public virtual FeeSlip FeeSlip { get; set; }
    }
}
