//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FeeType
    {
        public FeeType()
        {
            this.FeeDiscounts = new HashSet<FeeDiscount>();
            this.FeeSlipDetails = new HashSet<FeeSlipDetail>();
            this.FeeStructures = new HashSet<FeeStructure>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> AllowDiscount { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public Nullable<bool> IsOptional { get; set; }
    
         public virtual ICollection<FeeDiscount> FeeDiscounts { get; set; }
        public virtual ICollection<FeeSlipDetail> FeeSlipDetails { get; set; }
        public virtual ICollection<FeeStructure> FeeStructures { get; set; }
    }
}
