//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Homework
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public System.DateTime HomeworkDate { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public string AttachDocument { get; set; }
        public string description { get; set; }
        public int ClassSectionId { get; set; }
    
        public virtual ClassSection ClassSection { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
