//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class HostelAttendance
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int AttendanceTypeId { get; set; }
        public int HostelId { get; set; }
        public int HostleAdmId { get; set; }
    
        public virtual Hostel Hostel { get; set; }
        [ForeignKey("HostleAdmId")]
        public virtual HostelAdmission HostelAdmission { get; set; }
        [ForeignKey("AttendanceTypeId")]
        public virtual StudentAttendanceType StudentAttendanceType { get; set; }
    }
}
