//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Hostel")]
    public partial class Hostel
    {
        public Hostel()
        {
            this.HostelAdmissions = new HashSet<HostelAdmission>();
            this.HostelAttendances = new HashSet<HostelAttendance>();
            this.Rooms = new HashSet<Room>();
            this.Visitors = new HashSet<Visitor>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string HostelName { get; set; }
        public string TotalRooms { get; set; }
        public string TotalStudents { get; set; }
        public string Location { get; set; }
        public int CampusId { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual ICollection<HostelAdmission> HostelAdmissions { get; set; }
        public virtual ICollection<HostelAttendance> HostelAttendances { get; set; }
         public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<Visitor> Visitors { get; set; }
    }
}
