//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LibraryBookList
    {
        public LibraryBookList()
        {
            this.LibraryBookRecords = new HashSet<LibraryBookRecord>();
            this.LibraryIssuedBooks = new HashSet<LibraryIssuedBook>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int AccessionNo { get; set; }
        public string ClassficationNo { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Edition { get; set; }
        public string Subject { get; set; }
        public string YearOfPublishing { get; set; }
        public string VolumeNo { get; set; }
        public string Language { get; set; }
        public string Pages { get; set; }
        public string Price { get; set; }
        public string Source { get; set; }
        public string PresentPosition { get; set; }
        public bool IsIssuable { get; set; }
        public string Remarks { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Translator { get; set; }
        public string Cornor { get; set; }
    
        public virtual ICollection<LibraryBookRecord> LibraryBookRecords { get; set; }
        public virtual ICollection<LibraryIssuedBook> LibraryIssuedBooks { get; set; }
    }
}
