//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LibraryBookRecord
    {
        public LibraryBookRecord()
        {
            this.LibraryIssuedBooksToStaffs = new HashSet<LibraryIssuedBooksToStaff>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int LibraryId { get; set; }
        public int LibraryBookListId { get; set; }
        public string ShelfNo { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string UserId { get; set; }
        public bool isDeleted { get; set; }
        public bool isActive { get; set; }
    
        public virtual Library Library { get; set; }
        public virtual LibraryBookList LibraryBookList { get; set; }
       public virtual ICollection<LibraryIssuedBooksToStaff> LibraryIssuedBooksToStaffs { get; set; }
    }
}
