//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LibraryIssuedBooksToStaff
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int LibraryBookRecordId { get; set; }
        public decimal StaffID { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string BookCondition { get; set; }
        public string Remarks { get; set; }
    
        public virtual LibraryBookRecord LibraryBookRecord { get; set; }
        [ForeignKey("UserID")]
        public virtual  ApplicationUser AspNetUser { get; set; }
    }
}
