//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MenuAction
    {
        public MenuAction()
        {
            this.MenuItems = new HashSet<MenuItem>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string _Type { get; set; }
        public string Controller { get; set; }
        public string DisplayText { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<Privlidge> Privlidges { get; set; }
    }
}
