//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MessageRecord
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string TextMessage { get; set; }
        public string UserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int StudentID { get; set; }
        public Nullable<bool> PerSMSCharge { get; set; }

        public virtual Student Student { get; set; }
        [ForeignKey("UserID")]
        public virtual ApplicationUser AspNetUser { get; set; }
    }

    public partial class MessagePackage : BaseEntity
    {

        public DateTime PurchasedDate { get; set; }
        public string PackageName { get; set; }
        public int TotalMessages { get; set; }
        public int Validity { get; set; }
        public DateTime ExpireDate { get; set; }
        public bool IsEpired { get; set; }
        public DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public bool AmountPaid { get; set; }
    }

    public class MessageHistory 
    {
        [Key]
        public int Id { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Message { get; set; }
        public string Timestamp { get; set; }
        public string Operator { get; set; }
        public decimal Cost { get; set; }

        public override string ToString()
        {
            return $"Source:{Source} Destination:{Destination} Message:{Message} Timestamp:{Timestamp} Operator:{Operator} Cost: {Cost}"; ;
        }
        /// <summary>
        /// Get data in row for html table
        /// </summary>
        /// <returns><t><td>{Source}</td><td>{Destination} </td><td>{Message} </td><td>{Timestamp} </td><td>{Operator} </td><td>{Cost}</td></tr></returns>
        public string ToHtmlRow()
        {
            return $"<t><td>{Source}</td><td>{Destination} </td><td>{Message} </td><td>{Timestamp} </td><td>{Operator} </td><td>{Cost}</td></tr>"; ;
        }
    }
}
