//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MobileDevice
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        /// <summary>
        /// FCM Token
        /// </summary>
        public string SubscriptionId { get; set; }
        public int DeviceTypeId { get; set; }
        public string UserId { get; set; }
        public DateTime LastConnected { get; set; }

    }

    public partial class MobileMessage
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string FromId { get; set; }
        public string ToId { get; set; }
        public string Message { get; set; }
        public DateTime EntryDate { get; set; }
        public DateTime ReadDate { get; set; }
        public string MessageType { get; set; }
        public bool IsDeleted { get; set; }

        [ForeignKey("FromId")]
        public virtual  ApplicationUser Author { get; set; }

    }
}
