//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProfessionalTraining
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int StaffID { get; set; }
        public string UserID { get; set; }
        public string University { get; set; }
        public string Qualification { get; set; }
        public string Year { get; set; }
        public string Grade { get; set; }

        [ForeignKey("StaffID")]
        public virtual tbl_Employee tbl_Employee { get; set; }
        [ForeignKey("UserID")]
        public virtual  ApplicationUser AspNetUser { get; set; }
    }
}
