//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Rating
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int MasterID { get; set; }
        public Nullable<int> Star { get; set; }
        public Nullable<int> Star1 { get; set; }
        public Nullable<int> Star2 { get; set; }
        public Nullable<int> Star3 { get; set; }
        public Nullable<int> Star4 { get; set; }
        public Nullable<int> Star5 { get; set; }
        public Nullable<decimal> StaffID { get; set; }
        public Nullable<int> Total { get; set; }

        [ForeignKey("MasterID")]
        public virtual RatingMaster RatingMaster { get; set; }
    }
}
