//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RatingMaster
    {
         public RatingMaster()
        {
            this.Ratings = new HashSet<Rating>();
            this.RatingParticipants = new HashSet<RatingParticipant>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public int Year { get; set; }
        public string RatingType { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<RatingParticipant> RatingParticipants { get; set; }
    }
}
