//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ResultSummary
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int ExamHeldID { get; set; }
        public string CampusName { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> Enrollment { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Fail { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<int> S1 { get; set; }
        public Nullable<int> S2 { get; set; }
        public Nullable<int> S3 { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<int> C3 { get; set; }
        public Nullable<int> SB1 { get; set; }
        public Nullable<int> SB2 { get; set; }
        public Nullable<int> SB3 { get; set; }
        public Nullable<int> Appeared { get; set; }
    
        public virtual ExamHeld ExamHeld { get; set; }
    }
}
