//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Room
    {
         public Room()
        {
            this.HostelAdmissions = new HashSet<HostelAdmission>();
        }
       [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Floor { get; set; }
        public string Capacity { get; set; }
        public int RoomNo { get; set; }
        public int HostelId { get; set; }
    
        public virtual Hostel Hostel { get; set; }
        public virtual ICollection<HostelAdmission> HostelAdmissions { get; set; }
    }
}
