//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ScienceLabItem
    {
        public ScienceLabItem()
        {
            this.ScienceLabItemsStocks = new HashSet<ScienceLabItemsStock>();
            this.ScienceLabMissingItems = new HashSet<ScienceLabMissingItem>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string ItemName { get; set; }
    
        public virtual ICollection<ScienceLabItemsStock> ScienceLabItemsStocks { get; set; }
        public virtual ICollection<ScienceLabMissingItem> ScienceLabMissingItems { get; set; }
    }
}
