//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ScienceLabMissingItem
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int LIID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Remarks { get; set; }
        public string Demand { get; set; }
        public string Size { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }
        [ForeignKey("LIID")]
        public virtual ScienceLabItem ScienceLabItem { get; set; }
    }
}
