//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class StudentPreviousEducation
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int AdmissionID { get; set; }
        public string PreviousBoard { get; set; }
        public int YearOfPassing { get; set; }
        public string ObtainedMarks { get; set; }
        public string PreviousGroup { get; set; }
        public string RegNo { get; set; }
        public string Grade { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string Session { get; set; }
        public string RollNo { get; set; }
    
        public virtual Admission Admission { get; set; }
    }
}
