//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class StudentsTransport
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int DriverID { get; set; }
        public string PickPoint { get; set; }
        public string PickTime { get; set; }
        public string TripNumber { get; set; }
        public double Fare { get; set; }
        public string Started { get; set; }
        public string Closed { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Student Student { get; set; }
    }
}
