//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class StudentAttendanceType
    {
        public StudentAttendanceType()
        {
            this.HostelAttendances = new HashSet<HostelAttendance>();
            this.StudentAttendences = new HashSet<StudentAttendence>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string AttendanceName { get; set; }
        public double Fine { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<HostelAttendance> HostelAttendances { get; set; }
        public virtual ICollection<StudentAttendence> StudentAttendences { get; set; }
    }
}
