//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Student
    {
        public Student()
        {
            this.Admissions = new HashSet<Admission>();
            this.ComSubs = new HashSet<ComSub>();
            this.DOBChanges = new HashSet<DOBChanx>();
            this.ExpellDetails = new HashSet<ExpellDetail>();
            this.FeeDiscounts = new HashSet<FeeDiscount>();
            this.FreeAdmissions = new HashSet<FreeAdmission>();
            this.IssuedBoardCertificates = new HashSet<IssuedBoardCertificate>();
            this.IssuedBooks = new HashSet<IssuedBook>();
            this.IssuedCertificates = new HashSet<IssuedCertificate>();
            this.MessageRecords = new HashSet<MessageRecord>();
            this.OldJinnahians = new HashSet<OldJinnahian>();
            this.ParentsVisits = new HashSet<ParentsVisit>();
            this.ProhibitedMaterials = new HashSet<ProhibitedMaterial>();
            this.SelectedForCadetColleges = new HashSet<SelectedForCadetCollege>();
            this.SignatureSpecimen = new HashSet<SignatureSpeciman>();
            this.StudentComplaigns = new HashSet<StudentComplaign>();
            this.StudentMobiles = new HashSet<StudentMobile>();
            this.StudentPhotos = new HashSet<StudentPhoto>();
            this.StudentsTransports = new HashSet<StudentsTransport>();
            this.StudentsWarnings = new HashSet<StudentsWarning>();
            this.StudentThumbImpressions = new HashSet<StudentThumbImpression>();
            this.UnwantedClients = new HashSet<UnwantedClient>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string StudentName { get; set; }
        public string FName { get; set; }
        public string GuardianName { get; set; }
        public string StdRelation { get; set; }
        public string Email { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string MotherTongue { get; set; }
        public string LastIntitution { get; set; }
        public string Games { get; set; }
        public System.DateTime DOB { get; set; }
        public string PostalAddress { get; set; }
        public string OfficeTelephone { get; set; }
        public string PermenantAddress { get; set; }
        public string FatherQualification { get; set; }
        public string FatherProfession { get; set; }
        public string FatherNatureOfJob { get; set; }
        public string FatherDepartment { get; set; }
        public string MotherName { get; set; }
        public string MotherQualification { get; set; }
        public string MotherProfession { get; set; }
        public string MissingDocuments { get; set; }
        public string CNIC { get; set; }
        public int RegistrationNo { get; set; }
        public string Sex { get; set; }
        public string ResidanceTelephone { get; set; }
        public string Remarks { get; set; }
        public string GeneralRemarks { get; set; }
        public string DateForSubmission { get; set; }
        public string FatherAlive { get; set; }
        public string LiveWith { get; set; }
        public string Domicile { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string AdmittedClass { get; set; }
        public Nullable<double> FeeDiscount { get; set; }
        public string LastEditedBy { get; set; }
        public string LastEditedOn { get; set; }
        public Nullable<int> ApplyLateFee { get; set; }
        public string StudentCNIC { get; set; }
        public byte[] FatherPhoto { get; set; }
    
        
        public virtual ICollection<Admission> Admissions { get; set; }
        
        public virtual ICollection<ComSub> ComSubs { get; set; }
        
        public virtual ICollection<DOBChanx> DOBChanges { get; set; }
        
        public virtual ICollection<ExpellDetail> ExpellDetails { get; set; }
        
        public virtual ICollection<FeeDiscount> FeeDiscounts { get; set; }
        
        public virtual ICollection<FreeAdmission> FreeAdmissions { get; set; }
        
        public virtual ICollection<IssuedBoardCertificate> IssuedBoardCertificates { get; set; }
        
        public virtual ICollection<IssuedBook> IssuedBooks { get; set; }
        
        public virtual ICollection<IssuedCertificate> IssuedCertificates { get; set; }
        
        public virtual ICollection<MessageRecord> MessageRecords { get; set; }
        
        public virtual ICollection<OldJinnahian> OldJinnahians { get; set; }
        
        public virtual ICollection<ParentsVisit> ParentsVisits { get; set; }
        
        public virtual ICollection<ProhibitedMaterial> ProhibitedMaterials { get; set; }
        
        public virtual ICollection<SelectedForCadetCollege> SelectedForCadetColleges { get; set; }
        
        public virtual ICollection<SignatureSpeciman> SignatureSpecimen { get; set; }
        
        public virtual ICollection<StudentComplaign> StudentComplaigns { get; set; }
        
        public virtual ICollection<StudentMobile> StudentMobiles { get; set; }
        
        public virtual ICollection<StudentPhoto> StudentPhotos { get; set; }
        
        public virtual ICollection<StudentsTransport> StudentsTransports { get; set; }
        
        public virtual ICollection<StudentsWarning> StudentsWarnings { get; set; }
        
        public virtual ICollection<StudentThumbImpression> StudentThumbImpressions { get; set; }
        
        public virtual ICollection<UnwantedClient> UnwantedClients { get; set; }
    }
}
