//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tbl_MonthlySalary")]
    public partial class tbl_MonthlySalary
    {
        public tbl_MonthlySalary()
        {
            tbl_MonthlySalaryDetails = new HashSet<tbl_MonthlySalaryDetails>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public DateTime ForMonth { get; set; }
        public int EmployeeId { get; set; }
        public int? SalaryPackageId { get; set; }
        public DateTime EntryDate { get; set; }
        public string UserId { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        
        [ForeignKey("EmployeeId")]
        public virtual tbl_Employee Employee { get; set; }

        [ForeignKey("SalaryPackageId")]
        public virtual tbl_SalaryPackage SalaryPackage { get; set; }

        public ICollection<tbl_MonthlySalaryDetails> tbl_MonthlySalaryDetails { get; set; }
        public ICollection<tbl_SalaryPayment> SalaryPayments { get; set; }
    }
}
