//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tbl_SalaryPayment")]
    public partial class tbl_SalaryPayment
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int MonthlySalaryId { get; set; }
        public int LedgerId { get; set; }
        public string VoucherNo { get; set; }
        public DateTime EntryDate { get; set; }
        public decimal Amount { get; set; }
        public string Chequenumber { get; set; }
        public DateTime ChequeDate { get; set; }
        public string Narration { get; set; }
        public int VoucherTypeId { get; set; }
        public string UserId { get; set; }
        public DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        [ForeignKey("MonthlySalaryId")]
        public virtual tbl_MonthlySalary MonthlySalary { get; set; }

        [ForeignKey("VoucherTypeId")]
        public virtual tbl_VoucherType VoucherType { get; set; }

        [ForeignKey("LedgerId")]
        public virtual tbl_AccountLedger Ledger { get; set; }

    }
}
