//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_ReceiptDetails
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int ReceiptMasterId { get; set; }
        public int LedgerId { get; set; }
        public decimal Amount { get; set; }

        [ForeignKey("LedgerId")]
        public virtual tbl_AccountLedger Ledger { get; set; }

        [ForeignKey("ReceiptMasterId")]
        public virtual tbl_ReceiptMaster ReceiptMaster { get; set; }
    }
}
