//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_PaymentMaster
    {
        public tbl_PaymentMaster()
        {
            this.PaymentDetails = new HashSet<tbl_PaymentDetails>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int CampusId { get; set; }
        public string voucherNo { get; set; }
        public string invoiceNo { get; set; }
        public int LedgerId { get; set; }
        public string Narration { get; set; }
        public int VoucherTypeId { get; set; }
        public string ChequeNo { get; set; }
        public DateTime ChequeDate { get; set; }
        public DateTime VocherDate { get; set; }
        public DateTime EntryDate { get; set; }
        public string UserId { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }

        [ForeignKey("LedgerId")]
        public virtual tbl_AccountLedger Ledger { get; set; }
        [ForeignKey("VoucherTypeId")]
        public virtual tbl_VoucherType VoucherType { get; set; }
        public virtual ICollection<tbl_PaymentDetails> PaymentDetails { get; set; }
    }
}
