//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_Employee
    {
        public tbl_Employee()
        {
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.EmployeeExperinceSubjects = new HashSet<EmployeeExperinceSubject>();
            this.EmployeeExpriences = new HashSet<EmployeeExprience>();
            this.EmployeeShortLeaves = new HashSet<EmployeeShortLeave>();
            this.LeavedStaffs = new HashSet<LeavedStaff>();
            this.ProfessionalTrainings = new HashSet<ProfessionalTraining>();
            this.Qualifications = new HashSet<Qualification>();
            this.TeachingSubjects = new HashSet<TeachingSubject>();
            this.EmployeeThumbImpressions = new HashSet<EmployeeThumbImpression>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        //[Column("employeeId",TypeName ="Decimal(18,0)")]
        public int Id { get; set; }
        public int designationId { get; set; }
        public string employeeName { get; set; }
        public string employeeCode { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string maritalStatus { get; set; }
        public string gender { get; set; }
        public string qualification { get; set; }
        public string address { get; set; }
        public string phoneNumber { get; set; }
        public string mobileNumber { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> joiningDate { get; set; }
        public Nullable<System.DateTime> terminationDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string narration { get; set; }
        public string bloodGroup { get; set; }
        public string passportNo { get; set; }
        public Nullable<System.DateTime> passportExpiryDate { get; set; }
        public string labourCardNumber { get; set; }
        public Nullable<System.DateTime> labourCardExpiryDate { get; set; }
        public string visaNumber { get; set; }
        public Nullable<System.DateTime> visaExpiryDate { get; set; }
        public string salaryType { get; set; }
        public Nullable<decimal> dailyWage { get; set; }
        public string bankName { get; set; }
        public string branchName { get; set; }
        public string bankAccountNumber { get; set; }
        public string branchCode { get; set; }
        public string panNumber { get; set; }
        public string pfNumber { get; set; }
        public string esiNumber { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public Nullable<decimal> defaultPackageId { get; set; }
        public string Title { get; set; }
        public byte[] Photo { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public int CampusID { get; set; }
    
        public virtual Campus Campus { get; set; }
        
        [ForeignKey("designationId")]
        public virtual tbl_Designation tbl_Designation { get; set; }
        
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        
        public virtual ICollection<EmployeeExperinceSubject> EmployeeExperinceSubjects { get; set; }
        
        public virtual ICollection<EmployeeExprience> EmployeeExpriences { get; set; }
        
        public virtual ICollection<EmployeeShortLeave> EmployeeShortLeaves { get; set; }
        
        public virtual ICollection<LeavedStaff> LeavedStaffs { get; set; }
        
        public virtual ICollection<ProfessionalTraining> ProfessionalTrainings { get; set; }
        
        public virtual ICollection<Qualification> Qualifications { get; set; }
        
        public virtual ICollection<TeachingSubject> TeachingSubjects { get; set; }
        public virtual ICollection<EmployeeThumbImpression> EmployeeThumbImpressions { get; set; }
    }
}
