//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tbl_Company")]
    public partial class tbl_Company
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int companyId { get; set; }
        public string companyName { get; set; }
        public string mailingName { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string emailId { get; set; }
        public string web { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string pin { get; set; }
        public Nullable<decimal> currencyId { get; set; }
        public Nullable<System.DateTime> financialYearFrom { get; set; }
        public Nullable<System.DateTime> booksBeginingFrom { get; set; }
        public string tin { get; set; }
        public string cst { get; set; }
        public string pan { get; set; }
        public Nullable<System.DateTime> currentDate { get; set; }
        public byte[] logo { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
    }
}
