//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TeachingSubject")]
    public partial class TeachingSubject
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int CampusID { get; set; }
        public int ClassSectionID { get; set; }
        public int SubjectId { get; set; }
        public int StaffID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual ClassSection ClassSection { get; set; }
        public virtual Subject Subject { get; set; }
        [ForeignKey("StaffID")]
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
