//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TimeConsumptionForResultEntry
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int ClassID { get; set; }
        public int ExamHeldID { get; set; }
        public int ClassSubjectID { get; set; }
        public int CampusID { get; set; }
        public string UserID { get; set; }
        public int LMinute { get; set; }
        public int LHour { get; set; }

        [ForeignKey("UserID")]
        public virtual  ApplicationUser AspNetUser { get; set; }
    }
}
