//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Visitor
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        //[Column("Visitor_no")]
        public int Id { get; set; }
        public int CampusId { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public string Cnic { get; set; }
        public string Contact { get; set; }
        public string Description { get; set; }

        public int StudentRegNo { get; set; }
        public DateTime Date { get; set; }
        public string VistorType { get; set; }
        public DateTime EntryDate { get; set; }
        public string UserId { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
    }
}
