using System;
using System.Linq;

namespace Models
{
    public class EnumManager
    {
        public enum Imagetype
        {
          Logo,  Students, User, Employee, Father, Gaurdian, FatherSignature , GaurdianSignature
        }
        public enum Actions
        {
            Any = 0,
            View = 1,
            Save = 2,
            Edit = 3,
            Delete = 4
        }

        public enum AddNew
        {
            Campus,
            myClass,
            Section,
            Group,
            Subject
        }

        public enum BasicUserType
        {
            none = 0,
            User = 1,
            Campus = 2,
            Student = 4,
            Parent = 5,
            Employee = 7
        }

        public enum FeeTypes
        {
            Transport = 4,
            SMSCharges = 6,
            AttendanceFine = 7
        }

        [Flags]
        public enum Modules
        {
            ReceiveMonthlyFee = 1,
            frmVoucherType = 2,
            IndexDebitNote = 3,
            AccountLedger = 4,
            AddClassGroup = 5,
            HolidaySchedular = 6,
            frmSchedules = 7,
            ChangeClassSection = 8,
            AddClassSubjects = 9,
            frmCompanyCreation = 10,
            AddRole = 11,
            frmNewFinancialYear = 12,
            frmSuffixPrefixSettings = 13,
            GeneralSetting = 14,
            BackupData = 15,
            OrphenStudentViewer = 16,
            StudentEntry = 17,
            StudentsForm = 18,
            FrmPromoteStudent = 19,
            SearchContacts = 20,
            AdmissionWatingListForm = 21,
            StudnetTransportClassWiseViewer = 22,
            StudnetTransportDriverTripWiseViewer = 23,
            PhoneListViewer = 24,
            MissingDocuments = 25,
            DynamicHeadinReportVeiwer = 26,
            ComSubsWiseReportViewer = 27,
            IDCardViewerRep = 28,
            TransportCardVeiwer = 29,
            CertificateVeiwer = 30,
            BoardCertificateVeiwer = 31,
            AllInformationViewer = 32,
            ClasswiseStudentCampusViewer = 33,
            StudentdIdentificationViewer = 34,
            IssuedSLCViewer = 35,
            PresentstudentInformationViewer = 36,
            WithdrawalstudentInformationViewer = 37,
            SearchParticular = 38,
            GenderWiseStudentsdetail = 39,
            RegistrationReturnforBoardViewer = 40,
            LetterToStudentViewer = 41,
            ClassFeeGroupEntry = 42,
            FeeStructuresEntry = 43,
            FeeSlipEntry = 44,
            FeeSlipViewer = 45,
            StudentFeeDuestatmentViewer = 46,
            FeesGroupWiseList = 47,
            DuesStatementTotalVeiwer = 48,
            FeeRecordRegisterViewer = 49,
            ReceiptViewer = 50,
            ExemptFromLateFeeVeiwer = 51,
            NewExamHeld = 52,
            DateSheetEntry = 53,
            ResultEntry = 54,
            EditExamResult = 55,
            examRules = 56,
            AddRemarksDet = 57,
            MissingResultofStudent = 58,
            DateSheetViewer = 59,
            MarkSheetViewer = 60,
            ExamsDetail = 61,
            AwardListViewer = 62,
            WeeklyAwardListViewer = 63,
            ExamStatusReport = 64,
            UnEntereSubjectsResults = 65,
            GushwaraViewer = 66,
            SubjPosSummary = 67,
            ProgressReportVeiwer = 68,
            Attendance = 69,
            AttendanceByReg = 70,
            StudentAttendance = 71,
            AttendanceBySelectedClass = 72,
            AttendanceByClass = 73,
            StaffAutoAttendanceEntry = 74,
            StaffShortLeave = 75,
            StaffAttendance = 76,
            AttendanceViewer = 77,
            DailyAttendanceSheetClass = 78,
            dailyLeveGivenToStudentByStaff = 79,
            DailyAttendcewithTime = 80,
            StudentAttendanceRecord = 81,
            StudentConsectiveAttendanceViewer = 82,
            frmAttendanceViewer = 83,
            ShortLeaveView = 84,
            StaffAttendanceRecord = 85,
            frmStaffAttendanceTimeVeiwer = 86,
            frmMonthlyAttendanceReport = 87,
            frmTimeTableAutoGenerator = 88,
            frmSubjectTeaching = 89,
            frmChartOfAccount = 90,
            AddRemarks = 91,
            BankReconciliation = 92,
            EditFee = 93,
            frmMonthlySalarySettings = 94,
            IndexCreditNote = 95,
            ExeclSheetReadercs = 96,
            frmContraReport = 97,
            VeiwUnwantedClient = 98,
            DailyCashReportVeiwer = 99,
            AccountGroup = 100,
            CreateUsers = 101,
            Dashboard = 102,
            AllUsers = 103,
            frmChangeFinancialYear = 104,
            IncomeMapeVeiwer = 105,
            AcadimicComplainofStudents = 106,
            frmContraVoucher = 107,
            frmBillallocation = 108,
            Budget = 109,
            SendResults = 110,
            ComunicationSubs = 111,
            ListofParentsViewer = 112,
            SendMessagetoPublic = 113,
            frmEmployeeRegister = 114,
            EmployeeCreation = 115,
            Payhead = 116,
            TimeTableDesigner = 117,
            TimTableManual = 118,
            PeriodMasterEntry = 119,
            EditAccount = 120,
            StudentFeeEntry = 121,
            StaffEntry = 122,
            SearchStaff = 123,
            NewBoookEntry = 124,
            AddIncrement = 125,
            AdvanceSalaryPayment = 126,
            SubjectTeaching = 127,
            RemarksofStudents = 128,
            StaffListVeiwer = 129,
            frmDepartment = 130,
            Designation = 131,
            SalaryPackageCreation = 132,
            frmSalaryPackageRegister = 133,
            AdvancePayment = 134,
            frmMonthlySalaryVoucher = 135,
            frmBonusDeductionRegister = 136,
            RaitingMasterEntry = 137,
            RaitingEntry = 138,
            ActiveRatingMaster = 139,
            RatingDetail = 140,
            RatingList = 141,
            MonthlySalaryRegister = 142,
            frmAdvanceRegister = 143,
            frmDailySalaryVoucher = 144,
            PaySlips = 145,
            BonusDeduction = 146,
            DailySalaryRegister = 147,
            ReceiptVoucher = 148,
            frmBalanceSheet = 149,
            frmCashFlow = 150,
            frmEmployeeReport = 151,
            frmDailySalaryReport = 152,
            frmMonthlySalaryReport = 153,
            SendIssuedFee = 154,
            SendMessages = 155,
            SendReceivedFee = 156,
            BudgetVariance = 157,
            frmPaymentRegister = 158,
            PdcPayable = 159,
            ContraVoucher = 160,
            PDCReceivable = 161,
            JournalVoucher = 162,
            PdcClearance = 163,
            DeleteUser = 164,
            FeeByUsers = 165,
            frmReceiptReport = 166,
            ReceiveFeeFromStudent = 167,
            NewAcademicSession = 168,
            RebuildIndex = 169,
            ChangeAcademicSession = 170,
            CreateApplicationConfiguration = 171,
            ReseedIndex = 172,
            UploadStdData = 173,
            NoOfParents = 174,
            ExpenseRegister = 175,
            ExamsConfiguration = 176,
            RemarksConfiguration = 177,
            ResultMissingExams = 178,
            MeetingsAndAppointment = 179,
            AssignTeacher = 180,
            EditSchool = 181,
            CreateCampus = 182,
            PaymentVoucher = 183,
            MessageSubscribtion = 184,
            SendMessagebyStudentName = 185,
            SentResult = 186,
            SentComplaints = 187,
            SendAcademicComplaint = 188,
            SentPublicmessage = 189,
            SendCallLetter = 190,
            SendmessageIssuedFee = 191,
            SendAttendence = 192,
            SendReceiveFee = 193,
            SendMessagetoStaff = 194,
            StudentAlumni = 195,
            SendDateSheet = 196,
            SendMessageNew = 197,
            LedgerPosting = 198,
            ChartofAccounts = 199,
            ClassSection = 200,
            FeeType = 201,
            FeeGroup = 202,
            FeeReceipt = 203,
            ReciveFee = 204,
            HostelAdmission = 205,
            HostelAttendance = 206,
            Hostel = 207,
            feepaymentMethod = 208,
            ExamRemarks = 209,
            Room = 210,
            Student = 211,
            ExpellDetail = 212,
            UnExpell = 213,
            PromoteStudent = 214,
            Privileges = 215,
            visitor = 216,
            ClassWise = 217,
            DriverWise = 218,
            TripWise = 219,
            PhoneList = 220,
            ParentsList = 221,
            parentuser = 222,
            SubWiseList = 223,
            IDCard = 224,
            BirthCertificate = 225,
            StudentInformatoin = 226,
            ClassWiseList = 227,
            StudentIdentification = 228,
            PresentStudentsInformation = 229,
            WithdrewStudent = 230,
            ReportByGender = 231,
            ListofFreeAdmissions = 232,
            OrphanList = 233,
            DateSheet = 234,
            MarkSheet = 235,
            ResultGazzete = 236,
            AwardList = 237,
            AwardListblank = 238,
            weeklyAwardListblank = 239,
            RemarksEntrySheet = 240,
            RemarksSheet = 241,
            subjectlistwithnoresult = 242,
            ResultSummary = 243,
            ResultSubjectSummary = 244,
            ProgressReport = 245,
            MonthlyAttendance = 246,
            AttendanceSheetByClass = 247,
            AttendancesOnLeave = 248,
            DailyAttendanceTime = 249,
            AttendanceRecord = 250,
            ConsecutiveAttendance = 251,
            MonthlyAttendanceRegister = 252,
            ShortLeave = 253,
            DailyAttendanceTimeVeiwer = 254,
            FeeSlip = 255,
            DuesStatement = 256,
            ReceivedFeeByUsers = 257,
            ReceivedFee = 258,
            ClassWiseListOfFeeGroup = 259,
            FeeGroupList = 260,
            DuesStatementAmount = 261,
            FeeRecordRegister = 262,
            ReceiptCopy = 263,
            ExemptFromLateFee = 264,
            StudentRegister = 265
        }

        public enum Months
        {
            January = 1,
            February = 2,
            March = 3,
            April = 4,
            May = 5,
            June = 6,
            July = 7,
            August = 8,
            September = 9,
            October = 10,
            November = 11,
            December = 12
        }

        public enum newgroupEntry
        {
            none,
            Subject,
            Classes,
            Section,
            FeeType,
            FeeGroup,
            Exam,
            Campus,
            Group,
            Qualfication,
            Driver
        }

        public enum NotificationType
        {
            success,
            info,
            danger,
            teal,
            indigo
        }

        //public SelectList GetModulesList()
        //{
        //    var modules = new SelectList(Enum.GetValues(typeof(Modules)).Cast<Modules>().Select(v => new SelectListItem
        //    {
        //        Text = v.ToString(),
        //        Value = ((int) v).ToString()
        //    }).ToList(), "Value", "Text");
        //    return modules;
        //}
    }
}